#### ONLC: Python for Data Science

# Numpy Basics

Lets start with ordinary Python lists

Slices are important.

In [1]:
dir(__builtins__)[-10:]

['slice',
 'sorted',
 'staticmethod',
 'str',
 'sum',
 'super',
 'tuple',
 'type',
 'vars',
 'zip']

In [2]:
the_slice = slice(-10,None)
B = dir(__builtins__)

In [3]:
B[the_slice]

['slice',
 'sorted',
 'staticmethod',
 'str',
 'sum',
 'super',
 'tuple',
 'type',
 'vars',
 'zip']

### Lists of Lists

N-dimensional data possible through nesting lists inside lists ad infinitum.

In [4]:
twodee = [[1,2,3],[4,5,6]]
twodee

[[1, 2, 3], [4, 5, 6]]

In [5]:
twodee[0][1]

2

In [6]:
twodee[1]

[4, 5, 6]

In [7]:
twodee[1] = [11,12,13]
twodee

[[1, 2, 3], [11, 12, 13]]

### nd-array

In [8]:
import numpy as np

In [9]:
twodee2 = np.array(twodee)

In [10]:
twodee2

array([[ 1,  2,  3],
       [11, 12, 13]])

In [11]:
twodee2[0][1]

2

In [12]:
domain = np.arange(0, 10, 0.1)
domain

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [13]:
domain = np.linspace(0, 10, 100)
domain

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [14]:
np.random.randint?

In [15]:
d = np.random.randint(0,high=10,size=100)
d = d.reshape(10,10)
d

array([[1, 8, 4, 9, 7, 5, 7, 4, 4, 6],
       [0, 8, 8, 1, 3, 1, 1, 1, 5, 5],
       [4, 4, 0, 1, 7, 5, 0, 3, 0, 5],
       [9, 2, 2, 1, 1, 5, 7, 0, 7, 3],
       [9, 3, 6, 1, 1, 1, 9, 6, 8, 4],
       [7, 5, 1, 8, 6, 5, 5, 0, 4, 1],
       [7, 5, 2, 7, 8, 1, 8, 2, 3, 5],
       [6, 6, 7, 9, 9, 3, 3, 8, 5, 2],
       [6, 6, 8, 2, 1, 4, 8, 6, 0, 2],
       [7, 9, 1, 3, 3, 7, 1, 4, 2, 4]])

In [ ]:
d = np.random.rand(5,5)
d

array([[0.85930564, 0.14202602, 0.28541199, 0.41760864, 0.1876827 ],
       [0.45763691, 0.90500664, 0.13680092, 0.71258904, 0.88099979],
       [0.19515868, 0.07704   , 0.78070702, 0.64040566, 0.99357003],
       [0.8212632 , 0.77638838, 0.73669841, 0.00488603, 0.90954487],
       [0.90679756, 0.57041293, 0.58521067, 0.53891115, 0.01951126]])

In [ ]:
d = np.random.normal(size=25).reshape(5,5)
d

### MATLAB was here...

In [ ]:
twodee2[0,1]  # error if used with twodee

In [ ]:
twodee2[:,1]

In [ ]:
all_rows = slice(None, None)

In [ ]:
twodee2[all_rows, 1]

In [ ]:
view = twodee2[all_rows, 1]

In [ ]:
view[:] = [9, 10]  # slice assignment

In [ ]:
twodee2

### More Numpy Fun (page 34 ff)

In [ ]:
b = np.ones(3)
b

In [ ]:
b.ndim

In [ ]:
b.shape

In [ ]:
b = b.reshape(3,1)
b

In [ ]:
b.ndim

In [ ]:
b = b.reshape(1,3)
b

In [ ]:
b.ndim

In [ ]:
type(b[0,0])

In [ ]:
type(b)

In [ ]:
b = b.ravel()

In [ ]:
b

In [ ]:
b.shape

In [ ]:
d = np.array([(0,1,2,3),(10,11,12,13),(20,21,22,23)])

In [ ]:
d

In [ ]:
d.shape

In [ ]:
d.ndim

In [ ]:
row = d[1]
row

In [ ]:
element = d[1][1]

In [ ]:
element

In [ ]:
type(element)

In [ ]:
col = d[:,1]
col

In [ ]:
top_left_chunk = d[:2,:3]
top_left_chunk

In [ ]:
bottom_corner = d[-1,-1]
bottom_corner

In [ ]:
skip_cols = d[:,::2]
skip_cols

In [ ]:
row_slice = slice(None,2)
col_slice = slice(None,3)
top_left_chunk = d[row_slice, col_slice]
top_left_chunk

In [ ]:
e = d

In [ ]:
id(e) == id(d)

In [ ]:
col

In [ ]:
col[1] = 77

In [ ]:
d

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
domain = np.linspace(-5,5,100)

In [ ]:
result1 = np.cos(domain)
result2 = np.sin(domain)

In [ ]:
%matplotlib inline
plt.title("Plot")
plt.xlabel('x')
plt.ylabel('y')
plt.plot(domain, result1)
plt.plot(domain, result2);

In [ ]:
ar1 = np.zeros((4,4))
ar2 = np.ones((4,4))

In [ ]:
ar1

In [ ]:
np.hstack([ar1,ar2])

In [ ]:
np.vstack([ar1, ar2])

In [ ]:
ar3 = np.vstack([ar1, ar2])

In [ ]:
result = ar3[ar3 > 0]

In [ ]:
result

In [ ]:
result.shape

In [ ]:
np.where(ar3 > 0)